## KEY INSTRUCTIONS  

It is essential that you answer each cell by assigning the solution to QUESTION_# where # is the question number.

Each `QUESTION_#` will be preceeded by some key guidance and any libraries that may be required to complete and run the code successfully. 

KINDLY READ ALL THE QUESTIONS & GUIDANCE AS CAREFULLY AS YOU CAN TO GET AN UNDERSTANDING OF ALL REQUIREMENTS ON EACH QUESTION_#

## `ATTEMPT ALL FIRST SEVEN QUESTIONS AND AN ADDITIONAL ONE QUESTION FROM QUESTIONS 8 AND 9`

## TIME ALLOWED: 3 HOURS 

### Importing the neccessary libraries

In [114]:
#Import the neccessary Libraries by adding the following command in your Jupyter Notebook and run the cell

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


## Question 1 

Construct a matrix below ; 

$$\left[\begin{array}{ccc} 1 & 0.2 & 0.5 \\ 0.2 & 1 & 0.8 \\ 0.5 & 0.8 & 1 \end{array}\right]$$

as a NumPy array.


(a). Compute an Inversion of the matrix (`Transpose`) 

(b). Computer the (`determinant`) of the matrix if possible 

In [119]:
#Question_1(a) 
x = [[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]] #Assigning the matrix given to a variable x
y = np.array(x) #changing the variable into an array by assigning it to another variable
print(y) #Finding the transpose of the array y
print(y.T) #Finding the transpose of the array



[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [ ]:
#Question_1(b)
#Couldn't compute the determinant of y 

## Question 2

Construct a DataFrame starting from the matrix below

$$\left[\begin{array}{ccc} 1 & 0.2 & 0.5 \\ 0.2 & 1 & 0.8 \\ 0.5 & 0.8 & 1 \end{array}\right]$$

as a DataFrame with columns and index both equal to `['A', 'B', 'C']`. 

### Question 3: Given an n-dim array with enteries: 25, 2, 5;

1. Generate a numpy array x from the given entries
2. What is the shape of the array x
3. What is its transpose
4. Compute its $L^2$ Norm

In [86]:
#Question 3(1)
x = np.random.randint(10, size = (25, 2, 5)) #Creating the array x
x


array([[[8, 4, 1, 7, 8],
        [1, 2, 1, 1, 7]],

       [[5, 0, 4, 1, 1],
        [6, 6, 0, 2, 3]],

       [[7, 9, 2, 4, 9],
        [0, 6, 9, 2, 4]],

       [[7, 3, 0, 5, 4],
        [0, 2, 3, 1, 7]],

       [[1, 3, 4, 1, 7],
        [4, 0, 2, 7, 4]],

       [[0, 2, 6, 9, 2],
        [4, 9, 9, 5, 4]],

       [[4, 9, 8, 1, 5],
        [7, 0, 1, 3, 9]],

       [[2, 8, 2, 4, 8],
        [2, 9, 8, 7, 8]],

       [[2, 3, 3, 6, 0],
        [3, 6, 3, 9, 6]],

       [[3, 2, 2, 2, 6],
        [4, 6, 0, 4, 9]],

       [[2, 1, 6, 1, 7],
        [5, 6, 1, 6, 6]],

       [[6, 6, 2, 5, 2],
        [2, 3, 2, 9, 3]],

       [[8, 5, 4, 5, 1],
        [5, 8, 2, 9, 9]],

       [[5, 6, 4, 0, 8],
        [5, 5, 5, 1, 0]],

       [[0, 0, 0, 0, 7],
        [6, 3, 5, 4, 3]],

       [[4, 5, 1, 3, 6],
        [7, 4, 0, 0, 7]],

       [[3, 3, 0, 0, 9],
        [4, 4, 5, 8, 8]],

       [[0, 1, 5, 9, 9],
        [6, 1, 4, 0, 4]],

       [[7, 7, 7, 6, 2],
        [6, 0, 2, 7, 7]],

       [[2, 

In [89]:
#Question_3(2)
x.shape #Finding the shape of the array

(25, 2, 5)

In [92]:
#Question_3(3)
x.T #Finding the transpose of the array

array([[[8, 5, 7, 7, 1, 0, 4, 2, 2, 3, 2, 6, 8, 5, 0, 4, 3, 0, 7, 2, 3,
         8, 8, 1, 7],
        [1, 6, 0, 0, 4, 4, 7, 2, 3, 4, 5, 2, 5, 5, 6, 7, 4, 6, 6, 0, 4,
         4, 5, 5, 0]],

       [[4, 0, 9, 3, 3, 2, 9, 8, 3, 2, 1, 6, 5, 6, 0, 5, 3, 1, 7, 6, 8,
         8, 1, 7, 5],
        [2, 6, 6, 2, 0, 9, 0, 9, 6, 6, 6, 3, 8, 5, 3, 4, 4, 1, 0, 5, 1,
         3, 8, 9, 5]],

       [[1, 4, 2, 0, 4, 6, 8, 2, 3, 2, 6, 2, 4, 4, 0, 1, 0, 5, 7, 1, 0,
         6, 3, 8, 9],
        [1, 0, 9, 3, 2, 9, 1, 8, 3, 0, 1, 2, 2, 5, 5, 0, 5, 4, 2, 4, 5,
         6, 0, 9, 6]],

       [[7, 1, 4, 5, 1, 9, 1, 4, 6, 2, 1, 5, 5, 0, 0, 3, 0, 9, 6, 3, 1,
         3, 8, 0, 1],
        [1, 2, 2, 1, 7, 5, 3, 7, 9, 4, 6, 9, 9, 1, 4, 0, 8, 0, 7, 5, 0,
         5, 3, 6, 3]],

       [[8, 1, 9, 4, 7, 2, 5, 8, 0, 6, 7, 2, 1, 8, 7, 6, 9, 9, 2, 7, 5,
         4, 1, 7, 0],
        [7, 3, 4, 7, 4, 4, 9, 8, 6, 9, 6, 3, 9, 0, 3, 7, 8, 4, 7, 5, 6,
         9, 7, 8, 6]]])

### Question 4: Given a uniform random variable

Compute the Mean, variance, median, mode of the distribution

### Question 5: Given the following n-darrays, X1, X2 and X3

In [116]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

### (a) Find the ``ndim``, ``shape``, and ``size`` of 

In [109]:
#Working on x3 
print(x3) 
print(x3.ndim) #Finding the number of dimensions of x3
print(x3.shape) #Finding the shape of x3
print(x3.size) #Finding the size of x3

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
3
(3, 4, 5)
60


In [108]:
#Working on x2
print(x2)
print(x2.ndim) #Finding the number of dimensions of x2
print(x2.shape) #Finding the shape of x2
print(x2.size) #Finding the size of x2

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
2
(3, 4)
12


In [107]:
#Working on x1
print(x1)
print(x1.ndim)#Finding the number of dimensions of x2
print(x1.shape) #Finding the shape of x2
print(x1.size) #Finding the size of x2

[5 0 3 3 7 9]
1
(6,)
6


### (b) Modify the Values in matrix X2 in the index ``[0,0] = 12``

In [106]:
x2(0, 0)
x2

TypeError: 'numpy.ndarray' object is not callable

### Question 6:

Create the array below with a = np.arange(25).reshape(5, 5) and extract the elements indicated in blue.

(a). Extract all the numbers divisible by 3 using a boolean mask.

(b). Create a simple array, check type, size, dimension, and modify/ append values.


In [118]:
#Question_6
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
#Question_6(b)
import numpy as np
print(a.dtype) #Finding the type of a
print(a.size) #Finding the size of a
print(a.shape) #Finding the shape of a



int32
25
(5, 5)


### Question 7

Create the array below with
``a = np.arange(-15, 15).reshape(5, 6) ** 2``
and compute:
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum

In [145]:
w = np.arange(-15, 15).reshape(5, 6) ** 2
print(w)




[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]


TypeError: 'numpy.ndarray' object is not callable

### Question 8

Using the dataset named ``winequality-red.csv``. Compute



(a) Write a clean piece of code to compute the descriptive statistics 

(b) Write a simple piece of code to Sneak-Peek into dataset

(c) Write code to show Columns Names

(d) Write a piece of code to show Column Information

(e) Data cleaning always consists of the following methods :Removal of na values; Removal of null values; Removal of outliers if ``any``; Removal of redundant data

write clean pieces of code to:
1. na-values checking
2. null-values check
3. Redundant Data Removal

In [147]:
import pandas as pd
pd.read_csv('winequality-red.csv') #Importing the winequality-red.csv file that is in the folder
winequality = pd.read_csv('winequality-red.csv') #Assigning imy dataset to a variable
print(winequality)


In [153]:
#Question_8(a)
#Computing th e descriptive statistics of the dataset
print(winequality.mean)
print(winequality.median)
print(winequality.mode) 
print(winequality.var) # Finding the variance
print(winequality.std()) #finding the standard deviation

<bound method NDFrame._add_numeric_operations.<locals>.mean of       fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         

## Question 9

Load the covid-19 dataset in the CSV file `COVID-19 Cases.csv`, set the column `date` 
as the index, and ensure that `date` is a `DateTimeIndex`.

(a) Print a view of first 10 lines of the dataset

(b) Compute some summary statistics on at least three columns & create a new DataFrame out of the three columns computed statistics on. We can look at one column by explicitly passing it in the square brackets along with the column /field name in double quotes:

(c) Next we will isolate the data we want to focus our attention on by creating a new DataFrame from the source, and by applying a few filters against it. We want to isolate the records where all the following conditions are true. First the Daily Difference count is greater than zero. Next the Case Type should be Confirmed. Finally, the Country_Region should be only Italy: (HINT one can use this line to create a new DataFrame: `df_results = covid_df[(covid_df.Difference >0) & (covid_df.Case_Type == 'Confirmed') & (covid_df.Country_Region == 'Italy')]`)

Check whether the results are sorted by cases & ascending order to  well and accordingly, write the command to accomplish it:


## END 